PREFIX e: <http://example.org/fast/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (COUNT(*) AS ?n) WHERE { ?p e:author ?u ; e:tag ?t ; e:likes ?l . ?u e:city e:c3 . ?t e:broader ?b . ?l e:age ?age FILTER(?age > 80) }
