# Point lookup: one athlete's attributes
PREFIX o: <http://wallscope.co.uk/ontology/olympics/>
PREFIX r: <http://wallscope.co.uk/resource/olympics/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?p ?o WHERE { <http://wallscope.co.uk/resource/olympics/athlete/HermannSchreiber> ?p ?o }
