# Numeric filter + order: largest settlements
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?pop WHERE { ?s a dbo:Settlement ; dbo:populationTotal ?pop FILTER(?pop > 1000000) } ORDER BY DESC(?pop) LIMIT 50
