# Heads of something (Chair, Dean, Director ⊑ ∃isHeadOf)
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE { ?x :isHeadOf ?y }
