# Who works for an organisation (⊑ ∃worksFor.Organization)
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE { ?x :worksFor ?y . ?y rdf:type :Organization }
