# OWL2Bench Q3. Find the instances of Organization which is a Part Of any other Organization.
# Construct: isPartOf is a Transitive Object Property. Domain(Organization), Range(Organization)
# Profiles: EL, RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x ?y WHERE { ?x :isPartOf ?y }
