# OWL2Bench Q7. Find all the alumni of a University.
# Construct: hasAlumnus is an Inverse Object Property of hasDegreeFrom. Domain(University), Range(Person).
# Profiles: QL, RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x ?y WHERE { ?x :hasAlumnus ?y }
