# OWL2Bench Q11. Find all the instances who are advised by some other instance.
# Construct: isAdvisedBy is an Irreflexive Object Property. Domain(Person), Range(Person)
# Profiles: QL, RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x ?y WHERE { ?x :isAdvisedBy ?y }
