# OWL2Bench Q12. Find all the instances of class Person. A Person is union of Man and Woman.
# Construct: ObjectUnionOf
# Profiles: RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE { ?x rdf:type :Person}
