# OWL2Bench Q13. Find all the instances of class WomanCollege. WomanCollege is a College which has only Woman Students.
# Construct: AllValuesFrom
# Profiles: RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE { ?x rdf:type :WomanCollege}
