# OWL2Bench Q14. Find all the instances of class LeisureStudent. Leisure student is a Student who takes Maximum one course.
# Construct: ObjectMaxCardinality
# Profiles: RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE { ?x rdf:type :LeisureStudent}
