# OWL2Bench Q16. Find all the Organizations who has head.
# Construct: hasHead is a Functional Object Property. Domain(Organization), Range(Person).
# Profiles: RL, DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE {?x :hasHead ?y}
