# OWL2Bench Q17. Find all the instances of class UGStudent. UGStudent is a Student who enrolls in exactly one UGProgram.
# Construct: ObjectExactCardinality
# Profiles: DL
PREFIX : <https://kracr.iiitd.edu.in/OWL2Bench#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x WHERE {?x rdf:type :UGStudent}
