PREFIX e: <http://example.org/fast/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?p ?s WHERE { ?p e:score ?s } ORDER BY DESC(?s) ?p LIMIT 100
