[package]
name = "nrese-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nrese-core = { path = "../nrese-core" }
nrese-engine = { path = "../nrese-engine" }
nrese-reasoner = { path = "../nrese-reasoner" }
nrese-sparql = { path = "../nrese-sparql" }
oxrdf = "=0.3.3"
oxrdfio = "=0.2.4"
oxttl = "=0.2.3"
rayon = "1.10"
sha2 = "0.10.9"
sparesults = "=0.3.3"
spargebra = "=0.4.6"
thiserror.workspace = true
tracing.workspace = true
url = "2.5.7"

[dev-dependencies]
tempfile = "3.23.0"
