//! v1 (`rules-mvp`) test scenarios on reasoner v2, extracted from the v1 unit tests
//! before v1 was removed: each dataset, the inferences it expected and whether it
//! expected a consistency violation. v1-specific details (statistics, heuristic blame,
//! "unsupported construct" diagnostics) have no v2 counterpart.

use super::tests::scenario;

#[test]
fn consistency_disjoint_type_conflicts_detect_asserted_and_inferred_types() {
    scenario(
        &[
            (
                "http://example.com/Child",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://example.com/Parent",
            ),
            (
                "http://example.com/Parent",
                "http://www.w3.org/2002/07/owl#disjointWith",
                "http://example.com/Other",
            ),
            (
                "http://example.com/p",
                "http://www.w3.org/2000/01/rdf-schema#domain",
                "http://example.com/Other",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/spec",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Child",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn consistency_owl_nothing_conflicts_detect_explicit_nothing_type() {
    scenario(
        &[(
            "http://example.com/alice",
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "http://www.w3.org/2002/07/owl#Nothing",
        )],
        &[],
        Some(true),
    );
}

#[test]
fn consistency_owl_nothing_conflicts_detect_named_class_that_closes_to_nothing() {
    scenario(
        &[
            (
                "http://example.com/Impossible",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://www.w3.org/2002/07/owl#Nothing",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Impossible",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn equality_equality_index_groups_transitively_equivalent_terms() {
    scenario(
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/alicia",
            ),
            (
                "http://example.com/alicia",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/ally",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn identity_consistency_different_from_conflicts_with_asserted_same_as() {
    scenario(
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/alicia",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#differentFrom",
                "http://example.com/alicia",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn identity_consistency_different_from_conflicts_with_transitive_same_as_closure() {
    scenario(
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/alicia",
            ),
            (
                "http://example.com/alicia",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/ally",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#differentFrom",
                "http://example.com/ally",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn identity_inference_functional_property_implies_equality_between_objects() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#FunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/one",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/two",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn identity_inference_inverse_functional_property_implies_equality_between_subjects() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#InverseFunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/id",
            ),
            (
                "http://example.com/alicia",
                "http://example.com/p",
                "http://example.com/id",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn identity_inference_functional_property_merges_multiple_objects_into_one_cluster() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#FunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/one",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/two",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/three",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn property_chain_property_chain_plan_accepts_binary_named_node_list() {
    scenario(
        &[
            (
                "http://example.com/composed",
                "http://www.w3.org/2002/07/owl#propertyChainAxiom",
                "http://example.com/chain-head",
            ),
            (
                "http://example.com/chain-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p1",
            ),
            (
                "http://example.com/chain-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/chain-tail",
            ),
            (
                "http://example.com/chain-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p2",
            ),
            (
                "http://example.com/chain-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn property_chain_property_chain_plan_reports_longer_chain_as_bounded_unsupported() {
    scenario(
        &[
            (
                "http://example.com/composed",
                "http://www.w3.org/2002/07/owl#propertyChainAxiom",
                "http://example.com/chain-1",
            ),
            (
                "http://example.com/chain-1",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p1",
            ),
            (
                "http://example.com/chain-1",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/chain-2",
            ),
            (
                "http://example.com/chain-2",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p2",
            ),
            (
                "http://example.com/chain-2",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/chain-3",
            ),
            (
                "http://example.com/chain-3",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p3",
            ),
            (
                "http://example.com/chain-3",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn property_chain_property_chain_plan_reports_malformed_list() {
    scenario(
        &[
            (
                "http://example.com/composed",
                "http://www.w3.org/2002/07/owl#propertyChainAxiom",
                "http://example.com/chain-head",
            ),
            (
                "http://example.com/chain-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p1",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn property_consistency_detects_irreflexive_property_self_loop() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#IrreflexiveProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/alice",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn property_consistency_detects_asymmetric_property_reverse_pair() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#AsymmetricProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/bob",
            ),
            (
                "http://example.com/bob",
                "http://example.com/p",
                "http://example.com/alice",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn property_consistency_does_not_treat_functional_property_multiplicity_as_consistency_violation() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#FunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/one",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/two",
            ),
        ],
        &[],
        Some(false),
    );
}

#[test]
fn property_consistency_does_not_treat_inverse_functional_property_multiplicity_as_consistency_violation()
 {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#InverseFunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/id",
            ),
            (
                "http://example.com/bob",
                "http://example.com/p",
                "http://example.com/id",
            ),
        ],
        &[],
        Some(false),
    );
}

#[test]
fn property_consistency_detects_property_disjointness_collision() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/2002/07/owl#propertyDisjointWith",
                "http://example.com/q",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/bob",
            ),
            (
                "http://example.com/alice",
                "http://example.com/q",
                "http://example.com/bob",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn property_consistency_detects_property_disjointness_across_effective_subproperties() {
    scenario(
        &[
            (
                "http://example.com/p1",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/p",
            ),
            (
                "http://example.com/q1",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/q",
            ),
            (
                "http://example.com/p",
                "http://www.w3.org/2002/07/owl#propertyDisjointWith",
                "http://example.com/q",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p1",
                "http://example.com/bob",
            ),
            (
                "http://example.com/alice",
                "http://example.com/q1",
                "http://example.com/bob",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn property_consistency_does_not_duplicate_property_disjointness_when_axiom_is_bidirectional() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/2002/07/owl#propertyDisjointWith",
                "http://example.com/q",
            ),
            (
                "http://example.com/q",
                "http://www.w3.org/2002/07/owl#propertyDisjointWith",
                "http://example.com/p",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/bob",
            ),
            (
                "http://example.com/alice",
                "http://example.com/q",
                "http://example.com/bob",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_derives_subclass_and_type_closure() {
    scenario(
        &[
            (
                "http://example.com/Child",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://example.com/Parent",
            ),
            (
                "http://example.com/Parent",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://example.com/Ancestor",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Child",
            ),
        ],
        &[
            (
                "http://example.com/Child",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://example.com/Ancestor",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Parent",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Ancestor",
            ),
        ],
        None,
    );
}

#[test]
fn rules_reports_remaining_unsupported_construct_diagnostics() {
    scenario(
        &[(
            "http://example.com/restriction",
            "http://www.w3.org/2002/07/owl#allValuesFrom",
            "http://example.com/Target",
        )],
        &[],
        Some(false),
    );
}

#[test]
fn rules_derives_binary_property_chain_axiom_assertions() {
    scenario(
        &[
            (
                "http://example.com/ancestorLocatedIn",
                "http://www.w3.org/2002/07/owl#propertyChainAxiom",
                "http://example.com/chain-head",
            ),
            (
                "http://example.com/chain-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/parentOf",
            ),
            (
                "http://example.com/chain-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/chain-tail",
            ),
            (
                "http://example.com/chain-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/locatedIn",
            ),
            (
                "http://example.com/chain-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
            (
                "http://example.com/alice",
                "http://example.com/parentOf",
                "http://example.com/bob",
            ),
            (
                "http://example.com/bob",
                "http://example.com/locatedIn",
                "http://example.com/paris",
            ),
        ],
        &[(
            "http://example.com/alice",
            "http://example.com/ancestorLocatedIn",
            "http://example.com/paris",
        )],
        None,
    );
}

#[test]
fn rules_reports_unsupported_longer_property_chains() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/2002/07/owl#propertyChainAxiom",
                "http://example.com/chain-1",
            ),
            (
                "http://example.com/chain-1",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p1",
            ),
            (
                "http://example.com/chain-1",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/chain-2",
            ),
            (
                "http://example.com/chain-2",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p2",
            ),
            (
                "http://example.com/chain-2",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/chain-3",
            ),
            (
                "http://example.com/chain-3",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p3",
            ),
            (
                "http://example.com/chain-3",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
        ],
        &[],
        Some(false),
    );
}

#[test]
fn rules_supports_same_as_without_unsupported_diagnostic() {
    scenario(
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/alicia",
            ),
            (
                "http://example.com/alicia",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Person",
            ),
            (
                "http://example.com/alice",
                "http://example.com/knows",
                "http://example.com/bob",
            ),
        ],
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Person",
            ),
            (
                "http://example.com/alicia",
                "http://example.com/knows",
                "http://example.com/bob",
            ),
        ],
        Some(false),
    );
}

#[test]
fn rules_detects_disjoint_type_inconsistency() {
    scenario(
        &[
            (
                "http://example.com/Parent",
                "http://www.w3.org/2002/07/owl#disjointWith",
                "http://example.com/Other",
            ),
            (
                "http://example.com/Child",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://example.com/Parent",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Child",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Other",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_detects_irreflexive_property_inconsistency() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#IrreflexiveProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/alice",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_detects_asymmetric_property_inconsistency() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#AsymmetricProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/bob",
            ),
            (
                "http://example.com/bob",
                "http://example.com/p",
                "http://example.com/alice",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_detects_property_disjointness_inconsistency() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/2002/07/owl#propertyDisjointWith",
                "http://example.com/q",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/bob",
            ),
            (
                "http://example.com/alice",
                "http://example.com/q",
                "http://example.com/bob",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_derives_subproperty_transitive_closure() {
    scenario(
        &[
            (
                "http://example.com/p1",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/p2",
            ),
            (
                "http://example.com/p2",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/p3",
            ),
        ],
        &[(
            "http://example.com/p1",
            "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
            "http://example.com/p3",
        )],
        None,
    );
}

#[test]
fn rules_propagates_property_assertions_over_subproperty_hierarchy() {
    scenario(
        &[
            (
                "http://example.com/p1",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/p2",
            ),
            (
                "http://example.com/p2",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/p3",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p1",
                "http://example.com/bob",
            ),
        ],
        &[
            (
                "http://example.com/alice",
                "http://example.com/p2",
                "http://example.com/bob",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p3",
                "http://example.com/bob",
            ),
        ],
        None,
    );
}

#[test]
fn rules_infers_domain_and_range_types() {
    scenario(
        &[
            (
                "http://example.com/p1",
                "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
                "http://example.com/p2",
            ),
            (
                "http://example.com/p2",
                "http://www.w3.org/2000/01/rdf-schema#domain",
                "http://example.com/Person",
            ),
            (
                "http://example.com/p2",
                "http://www.w3.org/2000/01/rdf-schema#range",
                "http://example.com/Document",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p1",
                "http://example.com/spec",
            ),
        ],
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Person",
            ),
            (
                "http://example.com/spec",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Document",
            ),
        ],
        None,
    );
}

#[test]
fn rules_contract_equivalent_class_propagates_types_both_directions() {
    scenario(
        &[
            (
                "http://example.com/A",
                "http://www.w3.org/2002/07/owl#equivalentClass",
                "http://example.com/B",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/A",
            ),
        ],
        &[(
            "http://example.com/alice",
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "http://example.com/B",
        )],
        None,
    );
}

#[test]
fn rules_contract_equivalent_property_propagates_assertions() {
    scenario(
        &[
            (
                "http://example.com/p1",
                "http://www.w3.org/2002/07/owl#equivalentProperty",
                "http://example.com/p2",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p1",
                "http://example.com/bob",
            ),
        ],
        &[(
            "http://example.com/alice",
            "http://example.com/p2",
            "http://example.com/bob",
        )],
        None,
    );
}

#[test]
fn rules_contract_inverse_of_derives_inverse_assertion() {
    scenario(
        &[
            (
                "http://example.com/p1",
                "http://www.w3.org/2002/07/owl#inverseOf",
                "http://example.com/p2",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p1",
                "http://example.com/bob",
            ),
        ],
        &[(
            "http://example.com/bob",
            "http://example.com/p2",
            "http://example.com/alice",
        )],
        None,
    );
}

#[test]
fn rules_contract_symmetric_property_derives_reflected_assertion() {
    scenario(
        &[
            (
                "http://example.com/knows",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#SymmetricProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/knows",
                "http://example.com/bob",
            ),
        ],
        &[(
            "http://example.com/bob",
            "http://example.com/knows",
            "http://example.com/alice",
        )],
        None,
    );
}

#[test]
fn rules_contract_transitive_property_derives_composed_assertion() {
    scenario(
        &[
            (
                "http://example.com/ancestorOf",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#TransitiveProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/ancestorOf",
                "http://example.com/bob",
            ),
            (
                "http://example.com/bob",
                "http://example.com/ancestorOf",
                "http://example.com/carol",
            ),
        ],
        &[(
            "http://example.com/alice",
            "http://example.com/ancestorOf",
            "http://example.com/carol",
        )],
        None,
    );
}

#[test]
fn rules_reflexive_property_is_outside_owl2_rl() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#ReflexiveProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/knows",
                "http://example.com/bob",
            ),
        ],
        // Deliberate difference (design §6.3): v1 derived `x p x` for observed resources of
        // an owl:ReflexiveProperty; OWL 2 RL has no rule for it (reflexive properties are
        // outside the RL profile), and v2 follows the W3C rules.
        &[],
        None,
    );
}

#[test]
fn rules_rejects_different_from_conflict_against_same_as() {
    scenario(
        &[
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/alicia",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#differentFrom",
                "http://example.com/alicia",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_derives_same_as_from_functional_property() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#FunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/one",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/two",
            ),
        ],
        &[(
            "http://example.com/one",
            "http://www.w3.org/2002/07/owl#sameAs",
            "http://example.com/two",
        )],
        Some(false),
    );
}

#[test]
fn rules_derives_same_as_from_inverse_functional_property() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#InverseFunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/id",
            ),
            (
                "http://example.com/bob",
                "http://example.com/p",
                "http://example.com/id",
            ),
        ],
        &[(
            "http://example.com/alice",
            "http://www.w3.org/2002/07/owl#sameAs",
            "http://example.com/bob",
        )],
        Some(false),
    );
}

#[test]
fn rules_reuses_inferred_same_as_for_follow_on_type_propagation() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#InverseFunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/id",
            ),
            (
                "http://example.com/alicia",
                "http://example.com/p",
                "http://example.com/id",
            ),
            (
                "http://example.com/alicia",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Person",
            ),
        ],
        &[(
            "http://example.com/alice",
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "http://example.com/Person",
        )],
        Some(false),
    );
}

#[test]
fn rules_rejects_different_from_conflict_after_functional_equality_entailment() {
    scenario(
        &[
            (
                "http://example.com/p",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#FunctionalProperty",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/one",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p",
                "http://example.com/two",
            ),
            (
                "http://example.com/one",
                "http://www.w3.org/2002/07/owl#differentFrom",
                "http://example.com/two",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_rejects_instances_of_classes_closing_to_owl_nothing() {
    scenario(
        &[
            (
                "http://example.com/Impossible",
                "http://www.w3.org/2000/01/rdf-schema#subClassOf",
                "http://www.w3.org/2002/07/owl#Nothing",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Impossible",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_rejects_all_different_members_that_collapse_via_equality() {
    scenario(
        &[
            (
                "http://example.com/group",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#AllDifferent",
            ),
            (
                "http://example.com/group",
                "http://www.w3.org/2002/07/owl#members",
                "http://example.com/group-head",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/alice",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/group-tail",
            ),
            (
                "http://example.com/group-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/alicia",
            ),
            (
                "http://example.com/group-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/2002/07/owl#sameAs",
                "http://example.com/alicia",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_rejects_all_disjoint_classes_members_on_same_instance() {
    scenario(
        &[
            (
                "http://example.com/group",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#AllDisjointClasses",
            ),
            (
                "http://example.com/group",
                "http://www.w3.org/2002/07/owl#members",
                "http://example.com/group-head",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/Child",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/group-tail",
            ),
            (
                "http://example.com/group-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/Other",
            ),
            (
                "http://example.com/group-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Child",
            ),
            (
                "http://example.com/alice",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://example.com/Other",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_rejects_all_disjoint_properties_for_same_assertion_pair() {
    scenario(
        &[
            (
                "http://example.com/group",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#AllDisjointProperties",
            ),
            (
                "http://example.com/group",
                "http://www.w3.org/2002/07/owl#members",
                "http://example.com/group-head",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p1",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://example.com/group-tail",
            ),
            (
                "http://example.com/group-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/p2",
            ),
            (
                "http://example.com/group-tail",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p1",
                "http://example.com/bob",
            ),
            (
                "http://example.com/alice",
                "http://example.com/p2",
                "http://example.com/bob",
            ),
        ],
        &[],
        Some(true),
    );
}

#[test]
fn rules_reports_malformed_group_axiom_lists_deterministically() {
    scenario(
        &[
            (
                "http://example.com/group",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "http://www.w3.org/2002/07/owl#AllDifferent",
            ),
            (
                "http://example.com/group",
                "http://www.w3.org/2002/07/owl#members",
                "http://example.com/group-head",
            ),
            (
                "http://example.com/group-head",
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
                "http://example.com/alice",
            ),
        ],
        &[],
        None,
    );
}

#[test]
fn support_unsupported_constructs_are_reported_deterministically() {
    scenario(
        &[(
            "http://example.com/restriction",
            "http://www.w3.org/2002/07/owl#allValuesFrom",
            "http://example.com/Target",
        )],
        &[],
        None,
    );
}
