pub const CONFIG_PATH: &str = "NRESE_CONFIG_PATH";
pub const BIND_ADDR: &str = "NRESE_BIND_ADDR";
pub const DATA_DIR: &str = "NRESE_DATA_DIR";
pub const STORE_MODE: &str = "NRESE_STORE_MODE";
pub const REASONING_MODE: &str = "NRESE_REASONING_MODE";
pub const REASONER_RULES_MVP_PRESET: &str = "NRESE_REASONER_RULES_MVP_PRESET";
pub const REASONER_RULES_MVP_FEATURES: &str = "NRESE_REASONER_RULES_MVP_FEATURES";
pub const ONTOLOGY_PATH: &str = "NRESE_ONTOLOGY_PATH";

pub const MAX_QUERY_BYTES: &str = "NRESE_MAX_QUERY_BYTES";
pub const MAX_UPDATE_BYTES: &str = "NRESE_MAX_UPDATE_BYTES";
pub const MAX_RDF_UPLOAD_BYTES: &str = "NRESE_MAX_RDF_UPLOAD_BYTES";

pub const RATE_LIMIT_WINDOW_SECS: &str = "NRESE_RATE_LIMIT_WINDOW_SECS";
pub const READ_REQUESTS_PER_WINDOW: &str = "NRESE_READ_REQUESTS_PER_WINDOW";
pub const WRITE_REQUESTS_PER_WINDOW: &str = "NRESE_WRITE_REQUESTS_PER_WINDOW";
pub const ADMIN_REQUESTS_PER_WINDOW: &str = "NRESE_ADMIN_REQUESTS_PER_WINDOW";

pub const QUERY_TIMEOUT_MS: &str = "NRESE_QUERY_TIMEOUT_MS";
pub const UPDATE_TIMEOUT_MS: &str = "NRESE_UPDATE_TIMEOUT_MS";
pub const GRAPH_READ_TIMEOUT_MS: &str = "NRESE_GRAPH_READ_TIMEOUT_MS";
pub const GRAPH_WRITE_TIMEOUT_MS: &str = "NRESE_GRAPH_WRITE_TIMEOUT_MS";

pub const ENABLE_OPERATOR_UI: &str = "NRESE_ENABLE_OPERATOR_UI";
pub const ENABLE_METRICS: &str = "NRESE_ENABLE_METRICS";
pub const AI_ENABLED: &str = "NRESE_AI_ENABLED";
pub const AI_PROVIDER: &str = "NRESE_AI_PROVIDER";
pub const AI_MODEL: &str = "NRESE_AI_MODEL";
pub const AI_TIMEOUT_MS: &str = "NRESE_AI_TIMEOUT_MS";
pub const AI_MAX_SUGGESTIONS: &str = "NRESE_AI_MAX_SUGGESTIONS";
pub const AI_SYSTEM_PROMPT: &str = "NRESE_AI_SYSTEM_PROMPT";
pub const AI_GOOGLE_API_KEY: &str = "NRESE_AI_GOOGLE_API_KEY";
pub const AI_GOOGLE_API_BASE: &str = "NRESE_AI_GOOGLE_API_BASE";
pub const AI_OPENROUTER_API_KEY: &str = "NRESE_AI_OPENROUTER_API_KEY";
pub const AI_OPENROUTER_API_BASE: &str = "NRESE_AI_OPENROUTER_API_BASE";
pub const AI_OPENROUTER_SITE_URL: &str = "NRESE_AI_OPENROUTER_SITE_URL";
pub const AI_OPENROUTER_APP_NAME: &str = "NRESE_AI_OPENROUTER_APP_NAME";

pub const AUTH_MODE: &str = "NRESE_AUTH_MODE";
pub const AUTH_READ_TOKEN: &str = "NRESE_AUTH_READ_TOKEN";
pub const AUTH_ADMIN_TOKEN: &str = "NRESE_AUTH_ADMIN_TOKEN";
pub const AUTH_JWT_SECRET: &str = "NRESE_AUTH_JWT_SECRET";
pub const AUTH_JWT_ISSUER: &str = "NRESE_AUTH_JWT_ISSUER";
pub const AUTH_JWT_AUDIENCE: &str = "NRESE_AUTH_JWT_AUDIENCE";
pub const AUTH_JWT_READ_ROLE: &str = "NRESE_AUTH_JWT_READ_ROLE";
pub const AUTH_JWT_ADMIN_ROLE: &str = "NRESE_AUTH_JWT_ADMIN_ROLE";
pub const AUTH_JWT_LEEWAY_SECS: &str = "NRESE_AUTH_JWT_LEEWAY_SECS";
pub const AUTH_OIDC_INTROSPECTION_URL: &str = "NRESE_AUTH_OIDC_INTROSPECTION_URL";
pub const AUTH_OIDC_CLIENT_ID: &str = "NRESE_AUTH_OIDC_CLIENT_ID";
pub const AUTH_OIDC_CLIENT_SECRET: &str = "NRESE_AUTH_OIDC_CLIENT_SECRET";
pub const AUTH_OIDC_READ_ROLE: &str = "NRESE_AUTH_OIDC_READ_ROLE";
pub const AUTH_OIDC_ADMIN_ROLE: &str = "NRESE_AUTH_OIDC_ADMIN_ROLE";
pub const AUTH_OIDC_TIMEOUT_MS: &str = "NRESE_AUTH_OIDC_TIMEOUT_MS";
pub const AUTH_MTLS_SUBJECT_HEADER: &str = "NRESE_AUTH_MTLS_SUBJECT_HEADER";
pub const AUTH_MTLS_READ_SUBJECTS: &str = "NRESE_AUTH_MTLS_READ_SUBJECTS";
pub const AUTH_MTLS_ADMIN_SUBJECTS: &str = "NRESE_AUTH_MTLS_ADMIN_SUBJECTS";
