"""`suite.py ledger`: the run records under benches/runs/, one TOML file per run.

A run record says what a run covered and how each pair came out, never how fast: the raw
results stay in the git-ignored results directory (some vendors forbid publishing them),
the record is committed. benches/STATUS.md is generated from the records
(`suite.py status`), so what has been measured, where and from which commit survives on
every machine.

    suite.py ledger RESULTS-DIR [RESULTS-DIR ...]   write or refresh their records
    suite.py ledger --all                           every directory under benches/suite/results

Hand-written fields (purpose, baseline, findings, and commit or machine where a run
predates manifests) are kept when a record is refreshed. Records of kits outside the suite
(benches/reasoning/dl, the perf lab) are written by hand in the same format
(benches/runs/README.md).
"""
from __future__ import annotations

import argparse
import json
import tomllib
from collections import defaultdict
from pathlib import Path

from .schema import read

HAND_FIELDS = ("purpose", "baseline", "findings")
FALLBACK_FIELDS = ("commit", "machine", "host", "started", "finished", "protocol")
ORDER = ["id", "kit", "purpose", "baseline", "findings", "started", "finished", "host", "machine",
         "commit", "dirty", "protocol", "commands", "results", "publishable"]


def toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        return "[\n" + "".join(f"  {toml_value(v)},\n" for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{k} = {toml_value(v)}" for k, v in value.items()) + " }"
    return json.dumps(str(value), ensure_ascii=False)


def dump(record: dict) -> str:
    lines = ["# A run record (benches/runs/README.md). Generated by `suite.py ledger` from the run's",
             "# results.csv and manifest.json; purpose, baseline and findings are written by hand",
             "# and kept when the record is refreshed. Outcomes only: the numbers stay local.", ""]
    for key in ORDER + [k for k in record if k not in ORDER and k != "pairs"]:
        if key in record and record[key] is not None:
            lines.append(f"{key} = {toml_value(record[key])}")
    lines.append("")
    lines.append("pairs = [")
    for pair in record.get("pairs", []):
        lines.append(f"  {toml_value({k: v for k, v in pair.items() if v not in ('', None)})},")
    lines.append("]")
    return "\n".join(lines) + "\n"


def load_records(runs_dir: Path) -> list[dict]:
    records = []
    for path in sorted(runs_dir.glob("*.toml")):
        with open(path, "rb") as f:
            record = tomllib.load(f)
        record.setdefault("id", path.stem)
        records.append(record)
    return records


def outcome(rows: list[dict]) -> dict:
    """How one (workload, tier, system) came out in a run."""
    publish = rows[0]["publish"]
    live = [r for r in rows if r["status"] != "skipped"]
    regime = next((r["regime"] for r in live if r["regime"] not in ("", "-")), None) \
        or next((r["regime"] for r in rows if r["regime"] not in ("", "-")), "-")
    if not live:
        return {"regime": regime, "outcome": "skipped", "note": rows[0]["note"][:160]}
    if publish == "permission":
        return {"regime": regime, "outcome": "restricted",
                "note": "ran; results stay local until the vendor permits publishing"}
    loads = [r for r in live if r["task"] in ("load", "conformance")]
    ok_runs = {r["run"] for r in loads if r["status"] == "ok"}
    queries = [r for r in live if r["task"] == "query"]
    items = {r["item"] for r in queries}
    ok_items = {r["item"] for r in queries if r["status"] == "ok"}
    wrong = sorted({r["item"] for r in queries if r["status"] == "wrong"})
    others = [r for r in live if r["task"] not in ("load", "conformance", "query")]
    result = {"regime": regime, "runs": len(ok_runs)}
    if items:
        result["items"] = f"{len(ok_items)}/{len(items)}"
    if not ok_runs:
        statuses = {r["status"] for r in loads} or {"failed"}
        result["outcome"] = "timeout" if statuses == {"timeout"} else "failed"
        bad = next((r for r in loads if r["status"] != "ok"), None)
        if bad is not None and bad["note"]:
            result["note"] = bad["note"][:160]
    elif wrong:
        result["outcome"] = "wrong"
        result["note"] = "wrong answer counts: " + ", ".join(wrong)[:140]
    elif len(ok_items) < len(items) or any(r["status"] != "ok" for r in others + loads):
        result["outcome"] = "partial"
        failed = sorted(items - ok_items)
        if failed:
            result["note"] = "not ok: " + ", ".join(failed)[:150]
    else:
        result["outcome"] = "ok"
    return result


def from_results(directory: Path, root: Path) -> dict:
    rows = read(directory / "results.csv") if (directory / "results.csv").exists() else []
    manifest = {}
    if (directory / "manifest.json").exists():
        manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    invocations = manifest.get("invocations", [])
    try:
        shown = directory.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        shown = directory.name
    record: dict = {"id": directory.name, "kit": "suite", "results": f"{shown} (local, git-ignored)"}
    if invocations:
        first, last = invocations[0], invocations[-1]
        record["started"] = first["started"]
        record["finished"] = last.get("finished") or "unfinished"
        m = first.get("machine", {})
        record["host"] = m.get("host", "")
        docker = m.get("docker")
        record["machine"] = (f"{m.get('cpu')}, {m.get('logical_cores')} threads, {m.get('memory_gib')} GiB; "
                             f"{m.get('os')}" + (f"; Docker {docker['version']} ({docker['cpus']} CPUs, "
                                                 f"{docker['memory_gib']} GiB)" if docker else ""))
        commits = sorted({i["git"].get("commit") or "unknown" for i in invocations})
        record["commit"] = commits[0] if len(commits) == 1 else ", ".join(commits)
        record["dirty"] = max(i["git"].get("dirty", 0) for i in invocations)
        p = first["protocol"]
        record["protocol"] = (f"{p['runs']} runs, {p['query_runs']} measured query runs, cache {p['cache']}, "
                              f"order {p['order']} (seed {p['seed']}), load limit {p['timeout_s']} s, "
                              f"query limit {p['query_timeout_s']} s, {p['runtime']}")
        record["commands"] = ["suite.py run " + " ".join(i["argv"]) for i in invocations]
    elif rows:
        record["started"] = rows[0]["date"]
        record["host"] = rows[0]["host"]
        record["commit"] = "unknown (before run manifests)"
    by_pair: dict[tuple, list[dict]] = defaultdict(list)
    for r in rows:
        by_pair[(r["workload"], r["tier"], r["system"])].append(r)
    pairs = []
    for (workload, tier, system), group in sorted(by_pair.items()):
        pairs.append({"workload": workload, "tier": tier, "system": system} | outcome(group))
    record["pairs"] = pairs
    restricted = any(p["outcome"] == "restricted" for p in pairs)
    record["publishable"] = "free systems only" if restricted else "all"
    return record


def refresh(directory: Path, root: Path, runs_dir: Path) -> Path:
    record = from_results(directory, root)
    path = runs_dir / f"{record['id']}.toml"
    if path.exists():
        with open(path, "rb") as f:
            old = tomllib.load(f)
        for key in HAND_FIELDS:
            if key in old:
                record[key] = old[key]
        for key in FALLBACK_FIELDS:
            if key in old and (key not in record or str(record[key]).startswith("unknown")):
                record[key] = old[key]
    for key, default in (("purpose", ""), ("baseline", ""), ("findings", [])):
        record.setdefault(key, default)
    runs_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(dump(record), encoding="utf-8", newline="\n")
    return path


def main(argv: list[str], root: Path) -> int:
    p = argparse.ArgumentParser(prog="suite.py ledger", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("directories", nargs="*", type=Path, help="results directories")
    p.add_argument("--all", action="store_true", help="every directory under benches/suite/results")
    args = p.parse_args(argv)
    directories = list(args.directories)
    if args.all:
        directories += sorted(d for d in (root / "benches/suite/results").iterdir()
                              if (d / "results.csv").exists())
    if not directories:
        p.error("name results directories, or --all")
    for directory in directories:
        print(refresh(directory, root, root / "benches/runs").relative_to(root).as_posix())
    return 0
