PREFIX e: <http://example.org/fast/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?p ?u ?a WHERE { ?p e:author ?u . ?u e:follows ?v . ?v e:age ?a } LIMIT 1000
