PREFIX e: <http://example.org/fast/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT (COUNT(*) AS ?n) WHERE { ?s e:rel ?o . ?r rdf:reifies <<( ?s e:rel ?o )>> ; e:source e:src3 }
