mod access_api;
mod admin_dataset;
mod ai;
mod api_v1;
pub(crate) mod authentication;
mod classification;
mod console;
mod draft_check;
mod graph_store;
mod guard;
mod handlers;
mod media;
mod metrics;
mod mutation;
pub mod openapi;
mod operator_api;
mod operator_diagnostics;
mod operator_ui;
pub(crate) mod rdf4j;
mod rdf_payload;
mod reasoning_view;
mod repository;
pub(crate) mod request_metrics;
mod requests;
mod responses;
mod result_stream;
mod routes;
mod service_description;
mod shacl;
mod sparql;
mod tell;

pub use routes::router;
