mod admin_dataset;
mod ai;
mod classification;
mod console;
mod graph_store;
mod guard;
mod handlers;
mod media;
mod metrics;
mod mutation;
mod operator_api;
mod operator_diagnostics;
mod operator_ui;
mod rdf_payload;
mod reasoning_view;
mod requests;
mod responses;
mod result_stream;
mod routes;
mod service_description;
mod shacl;
mod sparql;
mod tell;

pub use routes::router;
